server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456yh
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.epoch.test.dao: debug